const dropTables= `DROP TABLE Users;
DROP TABLE Tasks;
DROP TABLE Meetings;`

const createTables = `CREATE TABLE IF NOT EXISTS
Users(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(20) UNIQUE NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(20) NOT NULL,
  state VARCHAR(20) DEFAULT 'active',
  online boolean DEFAULT false,
  verified boolean DEFAULT false,
  suspended boolean DEFAULT false
);

CREATE TABLE Tasks (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  assignerId  VARCHAR NOT NULL,
  assigneesId VARCHAR[] DEFAULT ARRAY[]::VARCHAR[] ,
  assigned boolean DEFAULT false,
  starts TIMESTAMP NOT NULL,
  ends TIMESTAMP NOT NULL,
  frozen boolean DEFAULT false

   );

CREATE TABLE Meetings (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR NOT NULL,
  starts TIMESTAMP NOT NULL,
  ends TIMESTAMP NOT NULL,
  attendess JSONB[] DEFAULT ARRAY[]::JSONB[]
 );
 
    `
  module.exports = {createTables,dropTables}